# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BkCiS0GND-0DCxkSlZcwSTv1y1E0haDJ
"""

!pip install pandas numpy matplotlib seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = sns.load_dataset('titanic')

print(df.head())

df.describe()

import pandas as pd
import seaborn as sns

df = sns.load_dataset('titanic')

# Har measure ek pandas built-in method se aata hai
print('Mean Age:', df['age'].mean())
print('Median Age:', df['age'].median())
print('Mode Age:', df['age'].mode()[0])   # [0] isliye kyunki mode ek Series return karta hai
print('Standard Deviation of Age:', df['age'].std())
print('Variance of Age:', df['age'].var())
print('Skewness of Age:', df['age'].skew())
print('Kurtosis of Age:', df['age'].kurt())

print(df['class'].value_counts(dropna=False))

plt.figure(figsize=(8, 4))
sns.heatmap(df.isnull(), cbar=False, cmap='viridis')
plt.title('Missing Value Map')
plt.tight_layout()
plt.show()

plt.figure(figsize=(6, 4))
sns.histplot(df['age'].dropna(), kde=True, bins=20, color='steelblue')
plt.title('Distribution of Age')
plt.xlabel('Age')
plt.tight_layout()
plt.show()

plt.figure(figsize=(6, 4))
sns.countplot(x='class', data=df, palette='Set2')
plt.title('Passenger Count by Class')
plt.tight_layout()
plt.show()

plt.figure(figsize=(6, 4))
sns.boxplot(y=df['fare'], color='lightcoral')
plt.title('Box Plot of Fare (Outlier Detection)')
plt.tight_layout()
plt.show()

plt.figure(figsize=(6, 4))
sns.scatterplot(x='age', y='fare', hue='survived', data=df, s=60)
plt.title('Age vs Fare by Survival')
plt.tight_layout()
plt.show()

survival_rate = df.groupby('class')['survived'].mean()
plt.figure(figsize=(6, 4))
survival_rate.plot(kind='bar', color='mediumseagreen')
plt.title('Survival Rate by Passenger Class')
plt.ylabel('Survival Rate')
plt.tight_layout()
plt.show()

numeric_df = df.select_dtypes(include=[np.number])
plt.figure(figsize=(6, 5))
sns.heatmap(numeric_df.corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap')
plt.tight_layout()
plt.show()

cols = ['survived', 'age', 'fare', 'sibsp', 'parch']
sns.pairplot(df[cols].dropna(), hue='survived')
plt.suptitle('Pair Plot of Numerical Features', y=1.02)
plt.show()